import { Layout } from '@/Layout/Layout'
import { MainPage } from '@/Layout/MainPage/MainPage'
import { getProducts } from '@/services/productsAPI'
import Head from 'next/head'


export default function Home() {

  return (
    <>
      <Head>
        <title>Your-store - the best store for you</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <MainPage />


      </Layout>


    </>
  )
}

